In [1]:
import numpy as np

In [3]:
np.load('beam_0.npy')

array([[[1.42558228e+10, 1.22631526e+10, 1.90133228e+10, ...,
         1.37079429e+10, 7.01144166e+09, 7.29241408e+08],
        [9.95058995e+09, 1.61661041e+10, 2.72625193e+10, ...,
         1.65078426e+10, 1.60677775e+10, 2.86336333e+09],
        [1.03587942e+10, 2.58423398e+10, 3.64176998e+10, ...,
         1.78954199e+10, 2.70313288e+10, 1.28272056e+10],
        ...,
        [6.43551590e+09, 2.91077181e+10, 3.28909332e+10, ...,
         2.19413197e+10, 4.22736364e+10, 3.64504637e+10],
        [8.25238016e+08, 1.52955884e+10, 2.79020605e+10, ...,
         2.35114250e+10, 3.65821829e+10, 2.47055176e+10],
        [2.37264538e+09, 4.40576307e+09, 1.79514266e+10, ...,
         2.09024205e+10, 2.64069222e+10, 1.49591276e+10]]])

In [4]:
np.load('../datasets/beam_intensities.npy')

array([[[1.42558228e+10, 1.22631526e+10, 1.90133228e+10, ...,
         1.37079429e+10, 7.01144166e+09, 7.29241408e+08],
        [9.95058995e+09, 1.61661041e+10, 2.72625193e+10, ...,
         1.65078426e+10, 1.60677775e+10, 2.86336333e+09],
        [1.03587942e+10, 2.58423398e+10, 3.64176998e+10, ...,
         1.78954199e+10, 2.70313288e+10, 1.28272056e+10],
        ...,
        [6.43551590e+09, 2.91077181e+10, 3.28909332e+10, ...,
         2.19413197e+10, 4.22736364e+10, 3.64504637e+10],
        [8.25238016e+08, 1.52955884e+10, 2.79020605e+10, ...,
         2.35114250e+10, 3.65821829e+10, 2.47055176e+10],
        [2.37264538e+09, 4.40576307e+09, 1.79514266e+10, ...,
         2.09024205e+10, 2.64069222e+10, 1.49591276e+10]],

       [[1.42558228e+10, 1.22631526e+10, 1.90133228e+10, ...,
         1.37079429e+10, 7.01144166e+09, 7.29241408e+08],
        [9.95058995e+09, 1.61661041e+10, 2.72625193e+10, ...,
         1.65078426e+10, 1.60677775e+10, 2.86336333e+09],
        [1.03587942e+10, 

In [5]:
np.load('../datasets/parameters.npy')

array([[0.99686143, 1.00187812],
       [0.99933644, 0.99953882],
       [0.99800489, 1.00267047],
       [0.99495872, 0.99572032],
       [1.0013249 , 0.99630233],
       [0.99560013, 0.99709234],
       [1.00046111, 0.99834556],
       [1.00375904, 1.00068522],
       [1.00223013, 1.0041981 ],
       [1.00455443, 1.00355869]])